baseURL = 'https://example.org/'
languageCode = 'en-us'



[params]
  [params.muffin]
    version = "0.1.0"
    # -----------------------------------------------------------------------------
    # Site-wide configuration parameters
    # 
    #   These can be overridden in the [params] of the site's hugo.toml file to 
    #   provide site-specific values.
    #
    [params.muffin.config]
      title = "Muffin Theme"
      description = "A replication of the Techdoc theme built with Tachyons CSS"

    # -----------------------------------------------------------------------------


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
